language: node_js
node_js:
  - "12.14.1"

branches:
  only:
    - master

cache:
  npm: true
  directories:
    - node_modules

before_script:
  - npm install -g firebase-tools
  - bash ./environment.sh

script:
  - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
